// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT8uyybgroSR4vOjXCYoDoJKjv1JAKcGo',
    appId: '1:1063756964149:web:e93d28a2247955f4f56c7c',
    messagingSenderId: '1063756964149',
    projectId: 'carrental-e18fe',
    authDomain: 'carrental-e18fe.firebaseapp.com',
    storageBucket: 'carrental-e18fe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASj8XToI1XMfoxcH7jdb0ayB47SZLVm6E',
    appId: '1:1063756964149:android:4fb4ec6aac52dc6ff56c7c',
    messagingSenderId: '1063756964149',
    projectId: 'carrental-e18fe',
    storageBucket: 'carrental-e18fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5amtq3NtixsqQQhvhCWrTcbPgGgfAvns',
    appId: '1:1063756964149:ios:c42c052037354944f56c7c',
    messagingSenderId: '1063756964149',
    projectId: 'carrental-e18fe',
    storageBucket: 'carrental-e18fe.appspot.com',
    iosClientId: '1063756964149-pmodjj8jntjlqrganvbojr9ecpi4i046.apps.googleusercontent.com',
    iosBundleId: 'com.example.carrental',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5amtq3NtixsqQQhvhCWrTcbPgGgfAvns',
    appId: '1:1063756964149:ios:c42c052037354944f56c7c',
    messagingSenderId: '1063756964149',
    projectId: 'carrental-e18fe',
    storageBucket: 'carrental-e18fe.appspot.com',
    iosClientId: '1063756964149-pmodjj8jntjlqrganvbojr9ecpi4i046.apps.googleusercontent.com',
    iosBundleId: 'com.example.carrental',
  );
}
